server:
#  port: 8080
  port: 8085
spring:
  application:
    name: cloud-consumer-test8080
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql驱动包
    type: com.alibaba.druid.pool.DruidDataSource # 当前数据源操作类型
    url: jdbc:mysql://localhost:3306/db01?characterEncoding=utf-8&useSSL=false&userUnicode=true&serverTimezone=GMT&allowPublicKeyRetrieval=true
    username: root
    password: peng0130

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.pkath2.springcloud.entities # 所有Entity别名类所在包
logging:
  level:
    com:
      pkath2:
        springcloud: DEBUG
